name: Hello Docker Action
description: Hello Docker Action
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: World
outputs:
  time:
    description: "The greeting time"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
