name: Workflow with Docker Containers

on: [push]

jobs:
  run-jdk-docker:
    runs-on: ubuntu-latest
    container:
      image: openjdk:11
    steps:
      - name: Log Java version
        run: javac --version

