name: Workflow with Events

on: 
  push:
    branches:
      - 03-trigger-workflows-with-events
  pull_request:
    types: [opened, closed, reopened, assigned]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World"
