name: Workflow with Custom Actions

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Hello action
        uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Lexis Nexis"
      - name: Log hello time
        run: 'echo "Time: ${{ steps.hello.outputs.time }}"'
  hello-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Hello action
        uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "Lexis Nexis"
      - name: Log hello time
        run: 'echo "Time: ${{ steps.hello.outputs.time }}"'

