name: Workflow with Filters

on:
  push:
    branches:
      - master
      - 0*-*
    tags:
      - v*
    paths:
      - "**.js"

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World"
