name: Deploy Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-alpine3.12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tar
        run: apk add tar
      - name: Cache node-modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist
  test:
    needs: [build]
    runs-on: ubuntu-latest
    container: node:16-alpine3.12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tar
        run: apk add tar
      - name: Cache node-modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install chromium
        run: apk add chromium
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        env:
          CHROME_BIN: "/usr/bin/chromium-browser"
        run: npm run test:ci
      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    container: node:16-alpine3.12
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      DEPLOY_DOMAIN: github-actions-lni-demo.surge.sh
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - name: Deploy to Surge
        run: npx surge --project ./dist/angular --domain ${{ env.DEPLOY_DOMAIN }}
