name: Basic Workflow

on:
  push:
  # schedule:
  #   - cron: "*/5 * * * *"
  repository_dispatch:
    types: [build]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World"
      - name: Echo message from event payload
        run: echo ${{ github.event.client_payload.message }}
